[env]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^6.0.0
	olikraus/U8g2@^2.34.18
	fbiego/ESP32Time@^2.0.0

[env:ttgo-lora32-v21-868]
build_flags = -D LORA_BAND_NATIVE=868

[env:ttgo-lora32-v21-433]
build_flags = -D LORA_BAND_NATIVE=433
